language: node_js
# When changing node version also update it on lines 26, 28 and 38.
node_js:
    - "4"
before_script:
    - npm install
script:
    - ./node_modules/buster/bin/buster generate --dir ./deployable 
